# For more details, see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  rubymotion:
    enabled: true

ratings:
  paths:
    - xenon-http/lib/**/*
    - xenon-routing/lib/**/*

exclude_paths:
  - examples/**/*
  - xenon-http/spec/**/*
  - xenon-routing/spec/**/*
  - vendor/**/*
