# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salutation.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Salutation" do
    optional :greeting, :string, 1
    optional :username, :string, 2
  end
end

Salutation = Google::Protobuf::DescriptorPool.generated_pool.lookup("Salutation").msgclass
